version: "3.8"
services:
  ldap:
    image: keshikid03/ldap21:group
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
      - "636:636"
    networks:
     - 2hisx
  ssh:
    image: keshikid03/ssh21:base
    container_name: ssh.edt.org
    hostname: ssh.edt.org
    ports:
      - "2022:22"
    networks:
     - 2hisx
  portainer:
    image: portainer/portainer
    container_name: portainer.edt.org
    hostname: portainer.edt.org
    ports: 
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock 
networks:
  2hisx:
